id: P003235
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1PD137867
  title: སི་ཁྲོན་བོད་རིག་པའི་ཞིབ་འཇུག ༼༣༽
  author: ''
  volumes:
    7af0c941b158478f876b7bb47844c791:
      image_group_id: I4PD4195
      title: ''
      volume_number: 1
      total_pages: 428
      base_file: v001.txt
