id: I35021E60
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T07:24:30+00:00'
last_modified: '2022-06-07T18:33:46.082400+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD137867
  title: སི་ཁྲོན་བོད་རིག་པའི་ཞིབ་འཇུག ༼༣༽
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    CAAA:
      image_group_id: I4PD4195
      title: ''
      total_pages: 428
      order: 1
      base_file: CAAA.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
